name: Build WFX Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Скачивание кода
      uses: actions/checkout@v4

    - name: Настройка CMake (x64)
      run: cmake -B build_x64 -A x64

    - name: Компиляция плагина
      run: cmake --build build_x64 --config Release

    - name: Загрузка готового плагина
      uses: actions/upload-artifact@v4
      with:
        name: Anomaly_Plugin_x64
        path: build_x64/Release/anomaly_db.wfx64
